# This workflow will create python packages when the master branch is tagged

name: Python Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build-dist:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    name: Build Python sdist and wheel
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 2
    - run: mkdir -p dist
    - name: Set up Python 3.10
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: "3.10"
    - name: Install build environment
      run: >-
        python -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m build --sdist --wheel --outdir dist/
    - name: Upload packages to artifacts
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        path: dist/*
    - name: Create GitHub pre-release
      id: gh_pre_release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      if: contains(github.ref_name, 'dev')
      with:
        files: dist/*
        prerelease: True
    - name: Create GitHub release draft
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      if: steps.gh_pre_release.conclusion == 'skipped'
      with:
        files: dist/*
        draft: True
