# This workflow will check for changed files, install Python dependencies and
# run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Tests

on:
  # run on each push to every branch of the repository but only on
  # pull requests to the 'master' and 'branch-*' branches
  push:
  pull_request:
    branches:
      - 'master'
      - 'branch-*'

permissions:
  contents: read

jobs:
  pre_check:
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    name: 'Check for code changes'
    runs-on: ubuntu-latest
    outputs:
      run_tests: ${{ steps.changes.outputs.python_test}}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 2
    - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
      id: changes
      with:
        filters: .github/filters.yml
        list-files: 'json'

  build:
    name: 'Run tests with Python'
    needs: pre_check
    if: needs.pre_check.outputs.run_tests == 'true'
    # we need to fix the ubuntu version until we drop Python 2.7 and 3.6
    runs-on: ubuntu-20.04
    strategy:
      # don't cancel running matrix tests when one test fails
      fail-fast: false
      matrix:
        # current supported Python versions (and 2.7 and 3.6 for legacy support)
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        # clone submodules as well
        submodules: 'recursive'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip installation
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-py_${{ matrix.python-version }}-${{ hashFiles('requirements.txt', 'tests/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-py_${{ matrix.python-version }}-
          ${{ runner.os }}-pip-

    - name: Install dependencies
      # create the virtual environment
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r tests/requirements.txt

    - name: Test with pytest
      id: pytest_run
      run: |
        pip freeze
        python -b -m pytest -v --cov=privacyidea --cov-report=xml tests/
      env:
        # silence some deprecation warnings
        PYTHONWARNINGS: "ignore:the imp module is deprecated in favour of importlib:DeprecationWarning,ignore:Please use assertRegex instead:DeprecationWarning"

    - name: Codecov upload
      if: ${{ steps.pytest_run.outcome == 'success' }}
      uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3.1.6
      with:
        files: ./coverage.xml
