name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / codespell
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: codespell
        uses: plettich/action-codespell@87ddfad515d60100b7c89d5840e03268c4fa76b3 # master
        with:
          reporter: github-pr-review
          level: info

